# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15a7957f66634f1e8c6719ddd29aae18ee7b8379ea156c7c7f48dda57e311ab4ee0165bf45f6d31a04605586dc1dfeb67ac9bc607fec1add211271d074b69385

test:
  secret_key_base: d8977b0b7611ec90f699f2563c3d61cf011eb2975427f8ac9afb9e01d76a4f9ce630f9b3b90a91e07afd14ccb388a0dfbe8103dd97cf4e902e10c807a3046210

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
